# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Merlions-Bloom-Indexer
networks:
- id: 747
  rpc_config:
    url: https://mainnet.evm.nodes.onflow.org	
  start_block: 1833705
  contracts:
  - name: MerlionsBloom
    address:
    # - 0x992ca660013553acfC1649418C490d91B4Ce5E42
    # - 0x2797Eb5a5E2E9d9F87aE905b307Dd71b296C105F
    - 0x5ddAA080C1B055b39609815d4aE522615b2f0Fd3
    handler: src/EventHandlers.ts
    events:
    - event: CoinFlipped(address indexed user, uint256 requestId, uint256 amount)
    - event: CoinRevealed(address indexed user, uint256 requestId, uint8 coinFace, uint256 prize)
    - event: RandomnessFulfilled(uint256 requestId, uint64 flowHeight, uint256 evmHeight, uint256 randomResult)
    - event: RandomnessRequested(uint256 requestId, uint64 flowHeight, uint256 evmHeight)
rollback_on_reorg: false
